title = "早安潛水 MorningDiver!"
# The default author for pages
author = "Morning Diver"
description = "客製化且彈性潛水學習方式"

# The URL the site will be built for
# start with "https://"
base_url = "/"

# The site theme to use.
# theme = ""

# The default language; used in feeds.
default_language = "en"

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "public"

# Whether dotfiles at the root level of the output directory are preserved when (re)building the site.
# Enabling this also prevents the deletion of the output folder itself on rebuilds.
preserve_dotfiles_in_output = false

# When set to "true", the Sass files in the `sass` directory in the site root are compiled.
# Sass files in theme directories are always compiled.
compile_sass = false

# When set to "true", the generated HTML files are minified.
minify_html = true

# A list of glob patterns specifying asset files to ignore when the content
# directory is processed. Defaults to none, which means that all asset files are
# copied over to the `public` directory.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*", "**/build_folder"]
ignored_content = []

# Similar to ignored_content, a list of glob patterns specifying asset files to
# ignore when the static directory is processed. Defaults to none, which means
# that all asset files are copied over to the `public` directory
ignored_static = []

# When set to "true", a feed is automatically generated.
generate_feeds = true

# The filenames to use for the feeds. Used as the template filenames, too.
# Defaults to ["atom.xml"], which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filenames = ["atom.xml", "rss.xml"]

# The number of articles to include in the feed. All items are included if
# this limit is not set (the default).
# feed_limit = 20

# When set to "true", files in the `static` directory are hard-linked. Useful for large
# static files. Note that for this to work, both `static` and the
# output directory need to be on the same filesystem. Note that the theme's `static`
# files are always copied, regardless of this setting.
hard_link_static = false

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [
    { name = "tags", feed = true, paginate_by = 10, display_name = "標籤" },
    { name = "categories", paginate_by = 5, display_name = "分類" },
]

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = false

# When set to "false", Sitemap.xml is not generated
generate_sitemap = true

# When set to "false", robots.txt is not generated
generate_robots_txt = true

# Configuration of the Markdown rendering
[markdown]
# When set to "true", all code blocks are highlighted.
# DO NOT set to true because we use prism
highlight_code = false

# A list of directories used to search for additional `.sublime-syntax` and `.tmTheme` files.
extra_syntaxes_and_themes = []

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = false

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = false

# Whether to set decoding="async" and loading="lazy" for all images
# When turned on, the alt text must be plain text.
# For example, `![xx](...)` is ok but `![*x*x](...)` isn’t ok
lazy_async_image = true

# Whether footnotes are rendered in the GitHub-style (at the bottom, with back references) or plain (in the place, where they are defined)
bottom_footnotes = true

# Configuration of the link checker.
[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = ["http://[2001:db8::]/"]

# Skip anchor checking for external URLs that start with these prefixes
skip_anchor_prefixes = ["https://caniuse.com/"]

# Treat internal link problems as either "error" or "warn", default is "error"
internal_level = "warn"

# Treat external link problems as either "error" or "warn", default is "error"
external_level = "warn"

# Various slugification strategies, see below for details
# Defaults to everything being a slug
[slugify]
paths = "safe"
taxonomies = "on"
anchors = "on"
# Whether to remove date prefixes for page path slugs.
# For example, content/posts/2016-10-08_a-post-with-dates.md => posts/a-post-with-dates
# When true, content/posts/2016-10-08_a-post-with-dates.md => posts/2016-10-08-a-post-with-dates
paths_keep_dates = false


[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the RFC3339 datetime of the page in the search index
include_date = false
# Whether to include the path of the page/section in the index (the permalink is always included)
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true
# At which code point to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100

# Wether to produce the search index as a javascript file or as a JSON file
# Accepted values:
# - "elasticlunr_javascript", "elasticlunr_json"
# - "fuse_javascript", "fuse_json"
index_format = "elasticlunr_javascript"

# Optional translation object for the default language
# Example:
#     default_language = "fr"
#
#     [translations]
#     title = "Un titre"
#
[translations]

# Additional languages definition
# You can define language specific config values and translations: 
# title, description, generate_feeds, feed_filenames, taxonomies, build_search_index
# as well as its own search configuration and translations (see above for details on those)
[languages]
# For example
# [languages.fr]
# title = "Mon blog"
# generate_feeds = true
# taxonomies = [
#    {name = "auteurs"},
#    {name = "tags"},
# ]
# build_search_index = false

# [languages.zh]

# [languages.zh.translations]
# title = "我的中文站点"

# You can put any kind of data here. The data
# will be accessible in all templates
# Example:
#     [extra]
#     author = "Famous author"
#
# author value will be available using {{ config.extra.author }} in templates
#
[extra]

# 站点设置
[extra.site]
# SEO 设置
seo = "一個潛水教學網站"
# 网站logo
logo = "/img/logo.webp"
# 网站favicon 尺寸比logo更小
favicon = "/img/logo.webp"
compliance_icp = "ISO/IEC 17065"

default_cover = "/img/lazyload.webp"
email = "yanganto@gmail.com"
start_year = "2025"

[extra.site.author]
avatar = "/img/avatar.jpg"
about_image = "/img/me.jpg"
mbti = 'dive'

# 是否启用页面统计
[extra.site.analytics]
# 关于页面展示访问量
stat_api = "https://stat-api-url"

# umami 监控
[extra.site.analytics.umami]
enable = false
# 监控的域名，避免被 localhost 统计 可选
domain = "your.domain.com"
# umami 服务地址
remote_url = "https:/stat-api-ur"
# 网站id 改成你的
id = "74859602-4481-4cb3-bad0-4e1fd9d23d24"
# js 地址
js = "/path/to/script.js"
# 追踪外部连接
track_external_link = true

# MS Clarity 监控
[extra.site.analytics.clarity]
enable = true
# 网站ID
id = ""

[extra.lib]
katex = true

[extra.feed]
# atom.xml 中显示文章全文
full_content_in_feed = false

# follow.is 验证源时使用
[extra.feed.follow]
# feed_id = "1234567890"
# user_id = "1234567890"

# 导航设置
[extra.nav]
# 菜单控制
# [extra.menus]
# pc端左侧菜单
pc_left_menu = true
# 移动左侧菜单
phone_left_menu = true
# 移动主菜单
phone_menu = true
# 站点名左侧菜单 默认只有主菜单，可前往【外观】—>【菜单】新建菜单组

# 导航栏右侧
[extra.nav.right]
# 开往按钮
travelling = false
# 右上角随機文章按钮
article = true
# 右上角切换主题模式按钮
dark_mode = true
# 右上角控制台按钮
console_enable = true
# 启用搜索
search = false
# 搜索引擎 选项: "meilisearch", "algolia"
search_engine = "algolia"

# Meilisearch 搜索
[extra.search.meilisearch]
# 服务器地址
host = ""
# search key
key = ""
# 索引名稱
index_name = ""

# Algolia 搜索
[extra.search.algolia]
app_id = ""
app_key = ""
index_name = ""

# 顶部设置
[extra.top]
# 瞬间说说
moment = false
# 顶部 Banner 显示
recent_top = true

# 首页第一屏，开启后会在页面的最上方新增一个第一屏
[extra.top.above]
enable = false
# 打字机显示的文字
typed = []
# 随機文字，如果配置了自定义文字，优先展示自定义文字
enable_typed_random = false
# 显示视频背景
enable_above_video = false
# 视频动态壁纸地址
index_video = ""
# PC端背景图地址
index_img = ""
# 移动端背景图地址
phone_index_img = ""

# 全局背景设置
[extra.top.global_background]
# 全局透明背景图
enable = false
# 全局透明背景视频动态壁纸
enable_above_video = false
# 全局背景图片地址
img = ""
# 全局背景视频地址
video = ""

# Banner 左侧
[extra.top.banner_left]
title_big = "<div class=\"banners-title-big\">Morning Diver</div><div class=\"banners-title-big\">適合你的潛水</div>"
title_small = ""

# 分组
[[extra.top.banner_left.category_groups]]
title = "推薦課程"
icon = "icon-book"
url = "/course"
colors = { light_one = "#358bff", light_two = "#15c6ff", dark_one = "#0653b8", dark_two = "#2fcbff" }

[[extra.top.banner_left.category_groups]]
title = "最近更新"
icon = "icon-fire"
url = "/tags/hot"
colors = { light_one = "#ff6655", light_two = "#ffbf37", dark_one = "#e22a16", dark_two = "#da980c" }

# Banner 右侧
[extra.top.banner_right]

# 今日推荐，在推荐文章前显示“今日推荐”模块
[extra.top.banner_right.today_recommend]
enable = true
# 文章路径，从content文件夹开始

# 推荐文章
[extra.top.banner_right.recommend_post]
# 类型： 最新文章 latest / 自定义推荐 custom
type = "custom"
# 推荐文章数量
max_posts = 6


# 导航设置
[extra.layout]

[extra.layout.navs]
# 导航条显示内容 Options: 分類 category, 標籤 tag, 自定义分類 custom-category, 自定义標籤 custom-tag, 自定义路径 custom-url
nav = "category"
# 自定义分類列表
nav_category = []
# 自定义標籤列表
nav_tag = []
# 自定义路径列表
nav_custom_url = []
# 更多按钮显示内容 Options: 隐藏 hide, 分類 categories, 標籤 tags, 自定义地址 customUrl
nav_more = "categories"
# 更多按钮跳转 自定义地址
nav_more_custom_url = ""

[extra.layout.post]
# 文章布局: "col1" (单列), "col2" (两列), or "col3" (三列)
columns = "col2"

# 封面位置: 上方 "top", 左侧 "left", 右侧 "right", 交替 "alternate" 建议单列时，将图片放在左右
cover_position = "top"

# 卡片效果  
[extra.layout.card]
# 首页文章卡片(擦亮效果)
polish_effect = false
# 鼠标悬停动画
hover_animation = true
# 阴影效果
shadow_effect = true

# 侧边栏
[extra.sidebar]
# 侧边栏位置 隐藏 hide-aside 右侧 right-aside 左侧 left-aside
location = "right-aside"

# 最新文章
recent_posts_count = 4

# 文章分類 小于 0 则展示全部分類
category_quantity = 0
# 文章標籤 小于 0 则展示全部標籤
tag_quantity = 6
# 文章归档 小于 0 则展示全部归档 目前没用等适配
archives_quantity = 0
# 標籤&归档&统计 (標籤按钮开关)
tags_switch = true
# 標籤&归档&统计 (归档按钮开关)
archive_switch = false

# 不同页面小部件设置
[extra.sidebar.widgets]
# "profile"个人卡片 "social"公众号 "power"爱发电赞助 "steam"Steam卡片 "music"音乐卡片 "friend-link"通讯录
# "recent-posts"最新文章 "visit-posts"熱門文章 "comments"最新评论 "categories"文章分類 "tags"文章標籤
# "stat"统计 "tags-stat"標籤&归档&统计 "adbox"广告区域 "custom_html"自定义

# 首页小部件
indexWidget = [
    { widget = "profile" },
    { widget = "social" },
    { widget = "comments" },
    { widget = "recent-posts" },
    { widget = "categories" },
    { widget = "tags" },
]

# 文章页面小部件
postWidget = [
    { widget = "profile" },
    { widget = "social" },
    { widget = "recent-posts" },
    { widget = "categories" },
]

# 分類页面小部件
taxonomyWidget = [
    { widget = "profile" },
    { widget = "social" },
    { widget = "comments" },
    { widget = "recent-posts" },
    { widget = "categories" },
    { widget = "tags" },
]

# 个人卡片
[extra.sidebar.profile]
# 样式 default one
profile_style = "one"
# 背景图片 提供自己的图片
background_img = "/img/sidebar/profile.webp"
# 描述信息 支持html
profile_desc = "早安潛水<br>SDI潛水認證系統<br>彈調彈性與靈活<br>打造專為你設計的潛水訓練課程"
# 社交媒体
socialMedia = [
    { icon = "icon-instagram", name = "Instagram", url = "https://www.instagram.com/morningdiver/" },
]

[extra.sidebar.social]
color = "#5756cb"
socialImg = ""
url = "https://www.instagram.com/morningdiver/"
socialImgFace = "/img/social/qr-purple.avif"
socialImgBack = "/img/social/qr-white.avif"

# 爱发电
[extra.sidebar.power]
# 赞助地址
powerLink = "/"
# 最大展示条数
showNum = 3

# 页脚栏
[extra.footer]
# 底部启用
enable = true
# 页脚高度
footer_banner_padding = 1
# 订阅
dingyue = true
# 主题
theme = true
# 关于
about = true
# icp备案
icp_icon = true
# 公网安备案
gongwangan = true
# 隐私
copyright = true
# 反馈
feedback = true
feedback_url = "mailto:yanganto@gmail.com"

# 云服务商 upyun_cloud aliyun_cloud tencent_cloud huawei_cloud custom_cloud
yunzhichi_list = ""
# 自定义云支持地址
yunzhichi_url = ""
# 自定义云支持跳转地址
yunzhichi_url_link = ""

[extra.footer.footer_bar]
# 是否显示
enable = false

# 社交媒体
[extra.footer.social_media]
# 中间 logo 是否启用
img_enable = true

# 左侧社交媒体
[[extra.footer.social_media.left]]
# 类型 icon 图标 custom 自定义 自定义类型支持 HTML 语法
# icon图标选择icon图标，svg代码或者图片(如果使用图片请输入完整img標籤)选择自定义
option_social_data = "icon"
# icon 图标 支持 HTML 语法 icon图标，svg代码，图片(如果使用图片请输入完整img標籤)
icon = "icon-envelope"
# 名稱
name = "Mail"
# 链接
url = "mailto:yanganto@gmail.com"

[[extra.footer.social_media.right]]
option_social_data = "icon"
icon = "icon-instagram"
name = "Instagram"
url = "https://www.instagram.com/morningdiver/"

[extra.footer.footer_group]
enable = true
num = 3

# 文章相關配置
[extra.post]
# 动态主色 文章主色匹配图片颜色
dynamicBackground = true
# 目录模糊效果
opacity = false
# 阅读建议 两篇 two 或六篇 six
recommendQuantity = "two"
# 版权样式 默认或样式一 default one
copyrightsStyle = "one"
# 最后更新时间
update_time = true

# Passage Tips Settings
[extra.post.passage_tip]
# 是否启用
enable = true
# 更新时间大于天数显示
day = 60

# 运营模式与责任
[extra.post.post_edit]
# 是否启用
enable_post_edit = false
# 运营模式与责任地址
post_edit_url = "/rss"

# 分享按钮
[extra.post.share_right]
# 启用分享手机访问二维码
mobile_edit = true
# 启用分享到微博
weibo_edit = false
# 启用复制链接
copyurl_edit = true

[extra.post.copyrights]
enable = true
copy_info = true
content = """
採用 <a target="_blank" href="/copyright">CC BY-NC-ND 4.0</a> 授權，轉載請註明 <a href="/" target="_blank" >早安潛水</a>
"""
reprintContent = """
本文是轉載文章，版權為早安潛水所有。
"""

# 相關網站设置
[extra.friend]
# 小标题
small_title = ""
# 大标题
big_title = "認識海洋的相關網站"
# 相關網站链接
links_url = "/friends"
# 评论开关
enable_comment = false
# 如果有本地logo，则优先使用本地logo
prefer_local_logo = false
# 是否使用 js 动态加载（推荐）
dynamic_render = true

[extra.course]
background_img = "/img/courses/AOW.jpg"
small_title = "課程宗旨"
big_title = "彈性且客製化的訓練"
detail = "安全永遠是我們的底線"
btn_title = ""
btn_url = ""

[extra.activity]
background_img = "/img/courses/AOW.jpg"
small_title = "活動宗旨"
big_title = "親近海洋，尊重海洋"
detail = "安全永遠是我們的底線"
btn_title = ""
btn_url = ""

# 关于设置
[extra.about]
# 小部件配置
widget_list = [
    # "hello-about",         # 我的问候
    "content-idea",        # 我的介绍&我的想法
    "author-career",       # 技能&职业生涯
    "personalities-photo", # 性格&图片
    # "textarea",            # 座右铭
    # "hobby",                # 爱好
    # "like-music",          # 关注偏好&音乐偏好
    # "statistics-map",      # 数据统计&作者相關信息
]

# 头像左侧个人標籤 (也会出现在首页个人简介中)
author_info_left_tags = [
    "🔍 喜歡探索水下世界",
    "🤛 潛水保持安全距離",
    "🏃 說走就走的行動派",
    # "🔯 全栈架构都在行",
]

# 头像右侧个人標籤 (也会出现在首页个人简介中)
author_info_right_tags = [
    # "🤖️ 本業軟體工程師", 
    # "🏠 除了潛水宅在家",
    # "🤝 喜歡",
    # "🎵 业余原創音乐人", 
]

# support HTML
content = "<div class=\"title1\">早安👋</div> <div class=\"title2\">歡迎加入<span class=\"inline-word\">Morning Diver</span>，成為專業的潛水員</div>"
idea = "<div class=\"author-content-item-tips\">專業潛水員</div> <h2>在<span class=\"inline-word\"/>潛水</span>的日子，只會<div class=\"mask\"> <span class=\"first-tips\" data-show=\"\">吃 Eat</span> <span>睡 Sleep</span> <span data-up=\"\">潛 Dive</span> </div> </h2>"

hello = "Morning!"

# 照片
[[extra.about.photos]]
url = "/img/logo.webp"
description = "照片"

# 职业生涯
[extra.about.careers]
title = "專業 耐心 創新"
bg = ""

[[extra.about.careers.tags]]
background = "#ff5f1f"
occupation = "SDI Instructor"

[[extra.about.careers.tags]]
background = "#ff5f1f"
occupation = "PADI Dive Master (#561728)"

[[extra.about.careers.tags]]
background = "#ff5f1f"
occupation = "YUHSIN Service & Maintenance Certificate (SMC2025E0090-002)"

[[extra.about.careers.tags]]
background = "#ff5f1f"
occupation = "EFR-Primary Care(CPR) & Sec Care(1st aid) (2409AR0252)"

[[extra.about.careers.tags]]
background = "#ff5f1f"
occupation = "SDI Equipment Specialist (#1653748)"

[[extra.about.careers.tags]]
background = "#1fffff"
occupation = "TDI Sidemount Diver (#1708793)"

[[extra.about.careers.tags]]
background = "#1fffff"
occupation = "PADI Rescue Diver"

[[extra.about.careers.tags]]
background = "#1fffff"
occupation = "PADI Advanced Open Water"

[[extra.about.careers.tags]]
background = "#1fffff"
occupation = "PADI Open Water"

# 样式设置
[extra.style]
# 颜色方案 system, dark, light
color_scheme = "system"
# 亮色主题基色
theme_light_skin = "#425AEF"
# 暗色主题基色
theme_dark_skin = "#f2b94b"
# 深色模式粒子效果
universe = true
# 全局字体 PingFang SC, Hiragino Sans GB, Microsoft YaHei
font_family = "PingFang SC"

# 繁简转换
[extra.style.translate]
# 启用繁简转换
enable = false
# 默认编码 2: 简体中文, 1: 繁体中文 
default_encoding = 1


# 代码块设置
[extra.code]
# 启用代码块
enable = true
# 启用标题
enable_title = true
# 启用分割线
enable_hr = true
# 启用行号
enable_line = true
# 启用复制
enable_copy = true
# 启用折叠
enable_expander = true
# 启用高度限制
enable_height_limit = false
# 高度限制
height_limit = 300
# 主题
theme_light = "one-dark"
# 暗色主题
theme_dark = "one-dark"
# 可选主题：one-dark one-light a11y-dark atom-dark base16-ateliersulphurpool.light cb coldark-cold coldark-dark coy-without-shadows darcula dracula duotone-dark duotone-earth duotone-forest duotone-light duotone-sea duotone-space ghcolors gruvbox-dark gruvbox-light holi-theme hopscotch lucario material-dark material-light material-oceanic night-owl nord pojoaque shades-of-purple solarized-dark-atom synthwave84 vs vsc-dark-plus xonokai z-touch 

# 小部件 右键菜单
[extra.tool]
keyboard = true

# 右键菜单
[extra.tool.right_menu]
# 启用
enable = true

# 右下角悬浮操作按钮
[extra.tool.rightside]
# 启用
enable = true
# 阅读模式
readmode = true

# 其他设置
[extra.other]
toc_enable = true
# 页面卡片顶部气泡升起效果
bubble_enable = true
# 渐变滚动条效果
scrollbar_linear_gradient_enable = false
# 標籤云随機颜色效果
tag_random_color_enable = true
# AVIF 图片优化，大幅降低图片尺寸
avif_enable = true

# 懒加载
[extra.other.lazyload]
enable = true
# 图片加载失败图
error_img = "/img/404.svg"
# 加载图片
loading_img = "/img/lazyload.svg"

# 加载动画
[extra.other.loading_box]
# 启用
enable = true
# 加载图片
img = "/img/logo.webp"
# 加载进度条
progress_bar = true

# 404 页面
[extra.other.error_404]
# 副标题
subtitle = "不好意思，找不到你要的文章"
# 背景
background = "/img/404.svg"

# 首页问候语
[extra.other.greeting]
# 启用
enable = false
# 设置
settings = []
