# 存放经常修改的配置，一般是网站的推荐文章、分類、標籤等信息

[post]
# 首页 Header 右侧推荐，建议 6 篇，填写 content 到 md 文件的相对地址
recommend_posts = [
    "courses/OW/index.md",
    "articles/neutral-buoyancy/index.md",
    "articles/softness-of-fin/index.md",
    "courses/OW/index.md",
    "articles/neutral-buoyancy/index.md",
    "articles/softness-of-fin/index.md",
]

# 首页 header 右侧
[post.today_recommend]
## 1， 推荐特定文章
# 文章地址
post_path = "courses/OW/index.md"
## 2. 跳转指定页面
# 跳转地址
url = "/"
# 大标题
title = "Lorem Ipsum"
# 背景图地址
cover = "/path/to/banner.jpg"
# 小标题
small_title = "今日推薦"


# 必须，下述標籤被用于网站导航中
[[post.tags]]
id = 'project'
index = 0
name = '項目'
[[post.tags]]
id = 'works'
index = 0
name = '作品'
[[post.tags]]
id = 'featured'
index = 0
name = '必看'
[[post.tags]]
id = 'hot'
index = 0
name = '最近'

[[post.tags]]
id = 'tech'
index = 1
name = '技術'
[[post.tags]]
id = 'training'
index = 2
name = '訓練'

[[post.categories]]
id = 'course'
index = 1
name = '課程'
[[post.categories]]
id = 'article'
index = 2
name = '文章'

[[post.taxonomies]]
id = 'categories'
index = 1
name = '分類'
[[post.taxonomies]]
id = 'tags'
index = 2
name = '標籤'

[menu]
# 顶部菜单
nav_menu = [
    { name = "服務項目", menus = [
        { name = "關於我們", href = "/about", icon = "icon-rocket", target = "_self" },
        { name = "潛水課程", href = "/course", icon = "icon-artstation", target = "_self" },
    ] },
    { name = "文章", menus = [
        { name = "全部文章", href = "/archives", icon = "icon-book-open", target = "_self" },
        { name = "分類列表", href = "/categories", icon = "icon-folder-open", target = "_self" },
        { name = "標籤列表", href = "/tags", icon = "icon-tags", target = "_self" },
        { name = "随機文章", href = "javascript:toRandomPost()", icon = "icon-dice", target = "_self" },
    ] },
    { name = "好站推薦", is_vertical = true, href = "/friends", menus = [] },
]

nav_left_menu = [
    { name = "快速選單", menus = [
        { name = "入門潛水員課程", href = "/courses/OW", icon = "icon-artstation", target = "_self" },
        { name = "關於我們", href = "/about", icon = "icon-rocket", target = "_self" },
    ] },
]

footer_menu = [
    { name = "服務項目", menus = [
        { name = "關於我們", href = "/about", target = "_self" },
        { name = "潛水課程", href = "/course", target = "_self" },
        { name = "聯絡我們", href = "/contact", target = "_self" },
    ] },
    { name = "文章", menus = [
        { name = "全部文章", href = "/archives", target = "_self" },
        { name = "分類列表", href = "/categories", target = "_self" },
        { name = "標籤列表", href = "/tags", target = "_self" },
    ] },
    { name = "文件表單", menus = [
        { name = "網站版權", href = "/copyright", target = "_self" },
    ] },
]

[course]
[[course.groups]]
name = "基礎課程"
description = "成為潛水員的必經之路"
items = [
    { name = "入門潛水員課程", img = "/img/courses/OW.png", model = "初級", button_title = "開課詳情", button_url = "/courses/OW" , description = "此課程又稱Open Water，是邁向海底世界的第一步。在課程中，你會學習基本的潛水裝備的操作方法，及意外的預防和排除方法" },
    { name = "進階潛水員課程", img = "/img/courses/AOW.jpg", model = "中級", description = "此課程又稱 Advanced Open Water，目的 是協助你成為獨當一面的潛水員。在課程中，除了更細緻的浮力控制及更細緻的踢動方法，你還會學習處理潛水的特殊情況，如深潛、夜潛、船潛 …" },
    { name = "救援潛水員課程", img = "/img/courses/AOW.jpg", model = "中級", description = "此課程又稱 Rescue Diver，是協助你成為可以信賴的潛伴，在課程中你會學習觀察同伴的狀況，經判斷後，可以提早進行預防。同時也會學習意外發生時的盡急處置，包含水下、水面及岸上。" },
]

[[course.groups]]
name = "專長課程"
description = "用不同方式潛水，獲得更多體驗"
items = [
    { name = "SDI高氧課程", img = "/img/courses/OW.png", model = "初級", description = "學習如何安全的使用高氧氣體來潛水，本課程沒有減壓理論的細節說明，旨在瞭解高氧的風險，並利用電腦錶安全的使用高氧氣體。" },
    { name = "TDI高氧課程", img = "/img/courses/AOW.jpg", model = "中級", description = "瞭解減壓理論並學習如何安全的使用高氧氣體來潛水，除了瞭解高氧的風險，安全的使用高氧的程序外，你將會有知識及能力調整電腦錶保守參數細節，以及瞭解在即使沒有電腦錶的情形下，怎麼對使用高氧氣體的風險進行換算，是紮實學會潛水不可少的理論知識。" },
]

[[course.groups]]
name = "領導課程"
description = "能力越強，責任越重"
items = [
    { name = "潛水長課程", img = "/img/courses/DM.jpg", model = "高級", description = "整體性的強化潛水技能，並且學習規劃潛水旅遊，在初級和中級課程中擔任助教的角色，照顧大家" },
]

# icon 无法将多种颜色的图形编程font，无法合并路径，使用起来麻烦，先将svg合并 https://svgsprit.es/
# 可以在 https://icomoon.io/ 导入 iconfont svg 文件然后重新打包 更新自己的图标
[holobios]
# 全局生效的 svg sprite
svg_sprite = "/img/icons/sprite.svg"

#[[holobios.items]]
#name = "唱歌"
## webfont class
##icon = "holobios-icon holobios-icon-sing"
## 图片连接
##logo = "/img/icons/sing.svg"
#bg_color = "#eb6840"
## 当前 item 生效的 svg sprite
##svg_sprite = "/img/icons/sprite.svg"
#svg_symbol_id = "sing"

[[holobios.items]]
name = "潛水"
bg_color = "#57b6e6"
svg_symbol_id = "divemask"

[[holobios.items]]
name = "早安潛水"
bg_color = "#f3fdfe"
logo = "/img/logo.webp"

[[holobios.items]]
name = "東方豹魴鮄"
bg_color = "#007386"
logo = "/holobios/Dactyloptena.jpg"

[[holobios.items]]
name = "揚旛蝴蝶魚"
bg_color = "#3e5054"
logo = "/holobios/butterfly_fish.jpg"

[[holobios.items]]
name = "硨磲貝"
bg_color = "#58d5dd"
logo = "/holobios/Tridacninae.jpg"

[[holobios.items]]
name = "玫瑰珊瑚"
bg_color = "#53574d"
logo = "/holobios/RoseCoral.jpg"

[[holobios.items]]
name = "珊瑚森林"
bg_color = "#003592"
logo = "/holobios/CoralForest.jpg"

[[holobios.items]]
name = "蝠鱝"
bg_color = "#003592"
logo = "/holobios/Menta.jpg"

[[holobios.items]]
name = "自由潛水"
bg_color = "#007386"
logo = "/holobios/FreeDive.jpg"

[[holobios.items]]
name = "海龜"
bg_color = "#007386"
logo = "/holobios/Turtle.jpg"

[[holobios.items]]
name = "小丑魚"
bg_color = "#007386"
logo = "/holobios/jerryfish.jpg"

[[holobios.items]]
name = "護士鯊"
bg_color = "#007386"
logo = "/holobios/Shark.jpg"

[[holobios.items]]
name = "火焰花枝"
bg_color = "#007386"
logo = "/holobios/Cuttlefish.jpg"
