# 存放经常修改的配置，一般是网站的推荐文章、分類、標籤等信息

[post]
# 首页 Header 右侧推荐，建议 6 篇，填写 content 到 md 文件的相对地址
recommend_posts = [
    "articles/misc/Lorem Ipsum/index.md",
    "articles/misc/Lorem Ipsum 2/index.md",
    "articles/misc/Lorem Ipsum 3/index.md",
    "articles/misc/Lorem Ipsum 4/index.md",
    "articles/misc/Lorem Ipsum 5/index.md",
    "articles/misc/Lorem Ipsum 6/index.md",
]

# 首页 header 右侧
[post.today_recommend]
## 1， 推荐特定文章
# 文章地址
post_path = "courses/OW/index.md"
## 2. 跳转指定页面
# 跳转地址
url = "/"
# 大标题
title = "Lorem Ipsum"
# 背景图地址
cover = "/path/to/banner.jpg"
# 小标题
small_title = "今日推薦"


# 必须，下述標籤被用于网站导航中
[[post.tags]]
id = 'project'
index = 0
name = '項目'
[[post.tags]]
id = 'works'
index = 0
name = '作品'
[[post.tags]]
id = 'featured'
index = 0
name = '必看'
[[post.tags]]
id = 'hot'
index = 0
name = '熱門'

# 可选，下述標籤仅用于文章分類
[[post.tags]]
id = 'tech'
index = 1
name = '技术'
[[post.tags]]
id = 'traning'
index = 2
name = '訓練'
[[post.tags]]
id = 'blog'
index = 3
name = '博客'

[[post.categories]]
id = 'course'
index = 1
name = '課程'
[[post.categories]]
id = 'misc'
index = 2
name = '雜記'

[[post.taxonomies]]
id = 'categories'
index = 1
name = '分類'
[[post.taxonomies]]
id = 'tags'
index = 2
name = '標籤'

[menu]
# 顶部菜单
nav_menu = [
    { name = "服務項目", menus = [
        { name = "關於我", href = "/about", icon = "icon-rocket", target = "_self" },
        { name = "潛水課程", href = "/course", icon = "icon-artstation", target = "_self" },
        { name = "我的項目", href = "/tags/project", icon = "icon-lightbulb", target = "_self" },
    ] },
    { name = "文章", menus = [
        { name = "全部文章", href = "/archives", icon = "icon-book-open", target = "_self" },
        { name = "分類列表", href = "/categories", icon = "icon-folder-open", target = "_self" },
        { name = "標籤列表", href = "/tags", icon = "icon-tags", target = "_self" },
        { name = "随機文章", href = "javascript:toRandomPost()", icon = "icon-artstation", target = "_self" },
    ] },
    { name = "推薦", is_vertical = true, href = "/friends", menus = [] },
]

# 导航栏最左侧折叠菜单，只支持两级菜单
# 优先使用icon image
nav_left_menu = [
    { name = "作品", menus = [
        { name = "Lorem Ipsum", href = "/articles/misc/lorem-ipsum", icon = "icon-music", target = "_self" },
        { name = "Lorem Ipsum", href = "/articles/misc/lorem-ipsum", icon = "icon-music", target = "_self" },
    ] },
]

# 底部菜单
footer_menu = [
    { name = "服務項目", menus = [
        { name = "關於我", href = "/about", target = "_self" },
        { name = "潛水課程", href = "/course", target = "_self" },
        { name = "我的項目", href = "/tags/project", target = "_self" },
    ] },
    { name = "文章", menus = [
        { name = "全部文章", href = "/archives", target = "_self" },
        { name = "分類列表", href = "/categories", target = "_self" },
        { name = "標籤列表", href = "/tags", target = "_self" },
        { name = "随機文章", href = "javascript:toRandomPost()" },
    ] },
    { name = "文件表單", menus = [
        { name = "網站版權", href = "/copyright", target = "_self" },
    ] },
]

[course]
[[course.groups]]
name = "基礎課程"
description = "成為潛水員的必經之路"
items = [
    { name = "潛水員課程", img = "/img/courses/OW.png", model = "初級", description = "邁向海底世界的第一步", button_title = "瞭解更多", button_url = "/courses/OW" },
    { name = "進階潛水員課程", img = "/img/courses/AOW.jpg", model = "中級", description = "成為獨當一面的潛水員" },
    { name = "救援潛水員", img = "/img/courses/AOW.jpg", model = "中級", description = "成為可以信賴的潛伴" },
]

[[course.groups]]
name = "專長課程"
description = "用不同方式潛水，獲得更多體驗"
items = [
    { name = "SDI高氧課程", img = "/img/courses/OW.png", model = "初級", description = "學習如何安全的使用高氧氣體來潛水" },
    { name = "TDI高氧課程", img = "/img/courses/AOW.jpg", model = "中級", description = "瞭解減壓理論並學習如何安全的使用高氧氣體來潛水" },
]

[[course.groups]]
name = "領導課程"
description = "能力越強，責任越重"
items = [
    { name = "潛水長課程", img = "/img/courses/DM.jpg", model = "高級", description = "學習規劃潛水旅遊，同時照顧大家" },
]

# icon 无法将多种颜色的图形编程font，无法合并路径，使用起来麻烦，先将svg合并 https://svgsprit.es/
# 可以在 https://icomoon.io/ 导入 iconfont svg 文件然后重新打包 更新自己的图标
[skill]
# 全局生效的 svg sprite
svg_sprite = "/img/icons/sprite.svg"

#[[skill.items]]
#name = "唱歌"
## webfont class
##icon = "skill-icon skill-icon-sing"
## 图片连接
##logo = "/img/icons/sing.svg"
#bg_color = "#eb6840"
## 当前 item 生效的 svg sprite
##svg_sprite = "/img/icons/sprite.svg"
#svg_symbol_id = "sing"

[[skill.items]]
name = "潛水"
bg_color = "#57b6e6"
svg_symbol_id = "divemask"

[[skill.items]]
name = "早安潛水"
bg_color = "#f3fdfe"
logo = "/img/logo.webp"

[[skill.items]]
name = "揚旛蝴蝶魚"
bg_color = "#3e5054"
logo = "/holobios/butterfly_fish.jpg"

[[skill.items]]
name = "東方豹魴鮄"
bg_color = "#57b6e6"
video = "/holobios/Dactyloptena.mp4"

[[skill.items]]
name = "潛水"
bg_color = "#57b6e6"
svg_symbol_id = "divemask"
[[skill.items]]
name = "潛水"
bg_color = "#57b6e6"
svg_symbol_id = "divemask"
[[skill.items]]
name = "潛水"
bg_color = "#57b6e6"
svg_symbol_id = "divemask"
[[skill.items]]
name = "潛水"
bg_color = "#57b6e6"
svg_symbol_id = "divemask"
[[skill.items]]
name = "潛水"
bg_color = "#57b6e6"
svg_symbol_id = "divemask"
[[skill.items]]
name = "潛水"
bg_color = "#57b6e6"
svg_symbol_id = "divemask"
[[skill.items]]
name = "潛水"
bg_color = "#57b6e6"
svg_symbol_id = "divemask"
[[skill.items]]
name = "潛水"
bg_color = "#57b6e6"
svg_symbol_id = "divemask"
